easy_admin:
    entities:
#        # List the entity class name you want to manage
        Managers:
            class: App\Entity\Manager
        Gamers:
            class: App\Entity\Gamer
        Tournois:
            class: App\Entity\Tournament